import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { ArrowDownRight, ArrowRight, ChevronDown } from 'lucide-react';
import { CtaPanel, PageHero, SectionHeading, WhatsAppAction } from '@/components/site-shell';
import { siteConfig } from '@/lib/site-config';

const services = [
  ['01', 'Laptops & desktops', 'New and refurbished work devices, selected around real roles and day-to-day use.'],
  ['02', 'Role-right-sized planning', 'A practical device mix for founders, finance, design, teaching, labs and shared spaces.'],
  ['03', 'Setup & deployment', 'Configuration, user-ready setup and deployment planning for teams and sites.'],
  ['04', 'Ongoing support', 'Maintenance, troubleshooting and support options shaped around your requirements.'],
  ['05', 'Monitors & accessories', 'Displays, docks, keyboards, headsets and the useful details around a workstation.'],
  ['06', 'Wi-Fi & networking', 'Network planning and equipment for dependable connectivity across your space.'],
  ['07', 'CCTV & security', 'CCTV capability and practical security planning for workplaces and campuses.'],
  ['08', 'AV & auditorium', 'Projectors and AV setup for meeting rooms, classrooms and auditoriums.'],
  ['09', 'Workspace essentials', 'Google Workspace, Microsoft 365 and email setup, plus security and backup planning. Servers and printers on request.'],
  ['10', 'Lifecycle options', 'Maintenance, replacement planning and buyback discussions when it is time to refresh.'],
];

function FrictionSection() {
  const points = [
    ['01', 'Too many specs to compare', 'Start with the work people do, then choose a sensible level of hardware.'],
    ['02', 'A device is only the beginning', 'Setup, connectivity, shared equipment and support all need to fit together.'],
    ['03', 'The next step is rarely obvious', 'Get one clear scope for buying, ongoing service and future refresh options.'],
  ];
  return <section className="section" style={{ paddingTop: 10 }}><div className="container-wide"><SectionHeading kicker="Why teams ask for help" title="IT buying gets complicated in the gaps." text="Different roles, mixed devices and disconnected setup can turn a simple purchase into a lot of coordination."/><div className="friction-grid">{points.map(([index,title,text])=><article className="surface friction-card" key={index}><span className="tile-index">{index} / FRICTION</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;
}

const sectors = [
  { title: 'Education & research', clients: ['Punjab Agricultural University (PAU), Ludhiana', 'Panjab University, Chandigarh', 'Government Schools in Punjab'] },
  { title: 'Healthcare & medical education', clients: ['PGIMER Chandigarh', 'AIIMS Bathinda (All India Institute of Medical Sciences, Bathinda)'] },
  { title: 'Transport & services', clients: ['Ex-servicemen Airlink Transport, Chanakyapuri, Delhi'] },
];

function ClientSection() {
  return <section className="section"><div className="container-wide"><SectionHeading kicker="Built for real-world teams" title="A partner for considered IT buying." text="We work across startup and institutional requirements. These names are shared as client references, not endorsements or project case studies." /><div className="client-groups">{sectors.map((sector) => <div className="client-group" key={sector.title}><h3>{sector.title}</h3>{sector.clients.map((client) => <p key={client}>{client}</p>)}</div>)}</div><p className="legal-note">Client names are listed as supplied. No individual projects, equipment assignments or outcomes are implied. Ex-servicemen Airlink Transport is shown pending confirmation of exact legal or trading name.</p></div></section>;
}

function ServiceTiles({ limit }: { limit?: number }) {
  return <div className="service-grid">{services.slice(0, limit).map(([n, title, text]) => <article className="surface service-tile" key={n}><span className="tile-index">{n} / CAPABILITY</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>;
}

export function HomePage() {
  return <>
    <main>
      <section className="hero page-enter"><div className="container-wide hero-grid">
        <div><div className="eyebrow">Your practical IT partner · Noida & North India</div><h1 className="display">You run the company.<br/><span style={{ color: 'hsl(var(--primary))' }}>We run your hardware.</span></h1><p className="hero-copy">From the right laptops to a ready-to-work setup and support that keeps things moving. One straightforward partner for your team’s IT.</p><div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 28 }}><Link href="/contact" className="button-primary">Talk through your needs <ArrowRight size={16}/></Link><Link href="/roles" className="button-outline">Build an IT checklist <ArrowDownRight size={16}/></Link><WhatsAppAction /></div><p className="form-hint" style={{ marginTop: 17 }}>For startups, organizations and institutions across Delhi NCR, Chandigarh and Punjab.</p></div>
        <div className="hero-art" aria-label="Illustration of a considered IT workspace" role="img"><div className="art-label"><span>IT, all in one place</span><span>BU / 001</span></div><div className="device-stack"><div className="device device-laptop"><div className="device-screen"/></div><div className="device device-phone"/><div className="device device-tower"/><div className="floating-note">PLAN / SOURCE / SET UP<br/>SUPPORT WHEN IT MATTERS</div></div></div>
      </div></section>
      <section className="container-wide" aria-label="Service commitments"><div className="trust-strip"><span>Warranty-backed options</span><span>GST invoice</span><span>Device setup included</span><span>Delhi NCR · Chandigarh · Punjab</span></div></section>
      <section className="section" style={{ paddingTop: 30 }}><div className="container-wide"><SectionHeading kicker="The whole hardware picture" title="Not just a box at your door." text="We help connect the dots between what your people do, what they need, and what it takes to keep it working."/><ServiceTiles limit={8}/><div style={{ marginTop: 25 }}><Link href="/services" className="button-quiet">See all service capabilities <ArrowRight size={16}/></Link></div></div></section>
      <FrictionSection/>
      <section className="split-band"><div className="container-wide split-inner"><div><div className="eyebrow" style={{ color:'#e5ad8a' }}>One partner, fewer loose ends</div><h2 className="display">From the first shortlist to the next refresh.</h2><p>We can help scope devices, source new or refurbished stock, set things up and talk through ongoing support. Start with what you need; the right level of help can follow.</p><Link href="/how-it-works" className="button-outline" style={{ color:'#f1eedf', borderColor:'rgba(243,240,220,.4)', marginTop:12 }}>How it works <ArrowRight size={16}/></Link></div><div className="split-list"><div className="split-row"><span>Plan around people and roles</span><span>01 / PLAN</span></div><div className="split-row"><span>Buy once or discuss managed service</span><span>02 / SOURCE</span></div><div className="split-row"><span>Set up devices and infrastructure</span><span>03 / READY</span></div><div className="split-row"><span>Support, maintain and plan refreshes</span><span>04 / CONTINUE</span></div></div></div></section>
      <ClientSection/>
      <section className="section" style={{ paddingTop: 8 }}><div className="container-wide"><SectionHeading kicker="Choose where to go next" title="Start with the option that fits."/><div className="home-shortcuts">
        <article className="surface shortcut-card"><div className="eyebrow">Compare approaches</div><h3>Plans & pricing</h3><p>Compare a one-time purchase with an ongoing managed service.</p><Link href="/plans" className="button-quiet">Compare plans <ArrowRight size={15}/></Link></article>
        <article className="surface shortcut-card"><div className="eyebrow">A considered second life</div><h3>Refurbished devices</h3><p>Understand condition grades, checks and product-specific terms.</p><Link href="/refurbished" className="button-quiet">Explore refurbished <ArrowRight size={15}/></Link></article>
        <article className="surface shortcut-card"><div className="eyebrow">See where we work</div><h3>Coverage & projects</h3><p>Discuss requirements across Delhi NCR, Chandigarh Tricity and Punjab.</p><Link href="/coverage" className="button-quiet">View coverage <ArrowRight size={15}/></Link></article>
      </div></div></section>
      <section className="section" style={{ paddingTop:10 }}><div className="container-wide"><SectionHeading kicker="A clearer way to start" title="A useful first plan, not a sales pitch." text="Answer a few practical questions about your team or site. The planner turns them into a checklist you can take into a conversation."/><Link href="/roles" className="button-primary">Try the IT plan estimator <ArrowRight size={16}/></Link></div></section>
      <section className="section" style={{ paddingTop: 0 }}><div className="container-wide faq-teaser"><div><div className="eyebrow">Still comparing options?</div><h2 className="display">A few answers before you start.</h2><p>See what to expect on refurbished condition, service scope, onsite support and more.</p></div><Link href="/faq" className="button-outline">Browse the FAQs <ArrowRight size={15}/></Link></div></section>
    </main><CtaPanel/>
  </>;
}

export function ServicesPage() {
  return <><PageHero kicker="What we can take off your plate" title="IT services that connect the dots." text="From individual workstations to site infrastructure, we help plan, source, set up and support the pieces that keep work moving."/><section className="section" style={{ paddingTop: 0 }}><div className="container-wide"><div className="service-list">{services.map(([n, title, text], index) => <article className="surface service-card" key={n}><span className="tile-index">{n} / {index < 3 ? 'ENDPOINTS' : index < 7 ? 'INFRASTRUCTURE' : 'LIFECYCLE'}</span><h2 className="display">{title}</h2><p>{text}</p></article>)}</div><p className="legal-note">Servers and printers can be discussed on request. Scope, availability and support arrangements are confirmed for each project.</p></div></section><CtaPanel/></>;
}

export function PlansPage() {
  return <><PageHero kicker="Two ways to work together" title="Buy it outright. Or make IT ongoing." text="The right arrangement depends on your cash flow, team size, refresh rhythm and how much support you want around the devices. We’ll help you compare without forcing a template."/><section className="section" style={{ paddingTop:0 }}><div className="container-wide"><div className="plan-grid">
    <article className="surface plan-card"><div className="eyebrow">Option 01 · Own your devices</div><h2 className="display">One-time purchase</h2><p>Choose devices and supporting equipment, then purchase them for your organization. Setup and support can be discussed as part of the scope.</p><div className="plan-price">Starting from ₹{siteConfig.startingBuy}</div><ul className="plan-points"><li>New or refurbished stock to consider</li><li>Role-based device planning</li><li>Setup and deployment options</li><li>Maintenance or future buyback discussion</li></ul><Link href="/contact" className="button-outline">Ask about a purchase <ArrowRight size={15}/></Link></article>
    <article className="surface plan-card featured"><div className="eyebrow" style={{ color:'#e5ad8a' }}>Option 02 · Keep support close</div><h2 className="display">Monthly managed service</h2><p>Discuss a monthly arrangement that brings hardware and agreed support together over time. Scope and availability are confirmed to fit your needs.</p><div className="plan-price">Starting from ₹{siteConfig.startingManaged}</div><ul className="plan-points"><li>Monthly service scope defined together</li><li>Device planning for roles and sites</li><li>Support and maintenance options</li><li>Refresh or replacement terms agreed up front</li></ul><Link href="/contact" className="button-outline" style={{color:'#f1eedf',borderColor:'rgba(243,240,220,.4)'}}>Discuss a managed plan <ArrowRight size={15}/></Link></article>
    </div><div className="comparison-wrap surface"><table className="comparison-table"><thead><tr><th scope="col">What to compare</th><th scope="col">One-time purchase</th><th scope="col">Monthly managed service</th></tr></thead><tbody><tr><th scope="row">Payment</th><td>One-time quote</td><td>Monthly fee agreed for the scope</td></tr><tr><th scope="row">Device ownership</th><td>Organization owns purchased devices</td><td>Ownership terms confirmed in the agreement</td></tr><tr><th scope="row">Setup</th><td>Confirmed in the project scope</td><td>Confirmed in the service scope</td></tr><tr><th scope="row">Support</th><td>Can be discussed with the order</td><td>Included only as agreed in writing</td></tr><tr><th scope="row">Refresh & replacement</th><td>Buyback can be discussed</td><td>Refresh and replacement terms agreed up front</td></tr></tbody></table></div><p className="legal-note">“Starting from” values are editable launch placeholders, not offers or price promises. Replace with approved pricing before publishing. Final price depends on device selection, quantity, scope and availability.</p></div></section><CtaPanel title="Not sure which way fits?" text="Share your team size, site needs and buying preference. We can map out the sensible questions first."/></>;
}

type Need = 'monitor' | 'network' | 'cctv' | 'av' | 'workspace' | 'support';
const needLabels: Record<Need, string> = { monitor:'Monitors and accessories', network:'Wi-Fi and networking', cctv:'CCTV and site security', av:'Projector and AV', workspace:'Email, workspace, security or backups', support:'Ongoing support and maintenance' };
const useCases: Record<string,string[]> = {
  Startup: ['Work laptops or desktops', 'Role-based device mix', 'Docking, monitors and accessories', 'Setup and deployment'],
  Office: ['Staff laptops or desktops', 'Shared workstations as needed', 'Monitors and accessories', 'Setup and deployment'],
  'School / campus': ['Staff and administration endpoints', 'Teaching or lab workstations as needed', 'Shared displays and accessories', 'Site connectivity planning'],
  'Healthcare / research': ['Staff and department endpoints', 'Specialist workstation requirements', 'Secure network and backup discussion', 'Deployment planning by site'],
  'Other organization': ['Core staff endpoints', 'Role-based device mix', 'Shared equipment as required', 'Deployment planning'],
};

const roleRecommendations = [
  ['Admin / documents', 'Everyday laptop or desktop', 'New or refurbished', 'Refurbished may fit standard document and email work; compare condition, warranty and support.'],
  ['Sales / support', 'Reliable portable laptop', 'New or refurbished to fit travel and support needs', 'Prioritize dependable calls, battery, webcam and headset support for people on the move.'],
  ['Developer', 'Performance-class workstation', 'New preferred; refurbished after configuration checks', 'Match memory, storage and graphics to the development tools and workload in use.'],
  ['Designer', 'Performance device with a suitable display', 'New or validated refurbished', 'Plan for creative software and display needs instead of buying one spec for everyone.'],
  ['Video editor', 'Higher-performance workstation', 'New preferred; refurbished only after workload checks', 'Size performance, memory, storage and display for the footage and software in use.'],
  ['Data / AI', 'Workload-specific workstation', 'Confirm new vs refurbished after toolchain review', 'Check local compute, cloud usage, data and security requirements before choosing.'],
  ['Founder / leadership', 'Portable everyday device', 'New or refurbished to match mobility and warranty needs', 'Keep core work smooth; add a monitor or premium device only when the role benefits from it.'],
  ['Teaching / auditorium', 'Staff devices plus room AV', 'Select for room compatibility and supportability', 'Check projector, sound, connectivity and how presenters will connect in each room.'],
  ['Research / healthcare', 'Workload-specific endpoints', 'Confirm software, peripherals and warranty first', 'Validate specialist software, peripherals, data and security needs before selecting devices.'],
  ['Transport / operations', 'Reliable office and shared endpoints', 'New or refurbished to fit usage and continuity needs', 'Consider shared access, connectivity, serviceability and the operational workflow.'],
];

function RoleRecommendations() {
  return <section className="section" style={{ paddingTop: 0 }}><div className="container-wide"><SectionHeading kicker="Right tech for every role" title="A good fit beats a bigger spec." text="These are starting points, not fixed product promises. Confirm the actual software, work pattern and availability before choosing."/><p className="role-promise">“We’ll tell you what you don’t need to buy.”</p><div className="role-card-grid">{roleRecommendations.map(([role,spec,choice,reason])=><article className="surface role-card" key={role}><div className="eyebrow">{role}</div><h3>{spec}</h3><div className="role-buy"><strong>New vs refurbished</strong><span>{choice}</span></div><p>{reason}</p></article>)}</div></div></section>;
}

export function RolesPage() {
  const [site, setSite] = useState('Startup');
  const [seats, setSeats] = useState(12);
  const [needs, setNeeds] = useState<Need[]>(['support']);
  const checklist = useMemo(() => [...(useCases[site] || useCases.Startup), ...(needs.includes('monitor') ? ['Monitor/accessory quantities by workstation'] : []), ...(needs.includes('network') ? ['Wi-Fi coverage and networking equipment review'] : []), ...(needs.includes('cctv') ? ['CCTV coverage and recording requirements review'] : []), ...(needs.includes('av') ? ['Projector, audio and room AV review'] : []), ...(needs.includes('workspace') ? ['Email/workspace, security and backup requirements'] : []), ...(needs.includes('support') ? ['Maintenance and ongoing support scope'] : [])], [site, needs]);
  const toggleNeed = (need: Need) => setNeeds((current) => current.includes(need) ? current.filter((item) => item !== need) : [...current, need]);
  return <><PageHero kicker="Interactive IT planner" title="Start with the people who’ll use it." text="We’ll tell you what you don’t need to buy. Build a practical equipment checklist for a team, campus or organization; it is a conversation starter, not a quote or a promise about exact quantities."/><section className="section" style={{ paddingTop:0 }}><div className="container-wide estimator-layout"><div className="surface estimator-form"><div className="eyebrow">01 / Your setup</div><div className="form-grid" style={{ marginTop:22 }}><div className="field"><label htmlFor="site-type">Use case / site type</label><select id="site-type" value={site} onChange={(event) => setSite(event.target.value)}>{Object.keys(useCases).map((name) => <option key={name}>{name}</option>)}</select></div><div className="field"><label htmlFor="seats">Seats / endpoints to plan around</label><input id="seats" type="number" min="1" max="9999" value={seats} onChange={(event) => setSeats(Math.max(1, Math.min(9999, Number(event.target.value) || 1)))} /></div><div className="field full"><label>What else is on your mind?</label><div className="check-options">{(Object.entries(needLabels) as [Need,string][]).map(([need,label]) => <label className="check-option" key={need}><input type="checkbox" checked={needs.includes(need)} onChange={() => toggleNeed(need)}/><span>{label}</span></label>)}</div></div></div><p className="form-hint" style={{ marginTop:18 }}>For larger or multi-site requirements, use the checklist as a starting point and tell us the details.</p></div><aside className="estimate-result surface"><div className="eyebrow" style={{color:'#e5ad8a'}}>02 / Your starting checklist</div><h2 className="display">{site} · {seats} {seats === 1 ? 'endpoint' : 'endpoints'}</h2><p>Use this outline to start a practical scope conversation.</p><ul className="checklist">{checklist.map((line,index)=><li key={`${line}-${index}`}><span className="check-dot">0{index+1}</span><span>{line}</span></li>)}</ul><Link href="/contact" className="button-primary" style={{background:'#d4a17f',color:'#1e3934'}}>Discuss this plan <ArrowRight size={15}/></Link><div className="legal-note" style={{color:'#c8d5ca'}}>Checklist only. Final equipment and quantities depend on roles, workflows, site requirements and availability.</div></aside></div></section><RoleRecommendations/><CtaPanel/></>;
}

export function RefurbishedPage() {
  const grades = [['A','Very good','Typically the cleanest cosmetic condition available in the refurbished range. Normal handling may be visible.'],['B','Good, signs of use','More noticeable cosmetic wear may be present. Devices should still be assessed for working condition.'],['C','Value / visible wear','Visible wear is expected. Ask for the exact condition, included items and functional checks before deciding.']];
  return <><PageHero kicker="A second life for good hardware" title="Refurbished, with the details up front." text="Refurbished devices can make sense when the condition, testing and fit are clear. We’ll discuss grading and available stock before you decide."/><section className="section" style={{ paddingTop:0 }}><div className="container-wide"><SectionHeading kicker="Condition is part of the spec" title="Know what each grade means." text="Grades are a practical visual guide, not a substitute for checking the actual unit and quote."/><div className="grade-grid">{grades.map(([letter,title,text])=><article className="surface grade-card" key={letter}><div className="grade-letter">{letter}</div><h3 className="display">{title}</h3><p>{text}</p></article>)}</div><div className="content-grid" style={{marginTop:18}}><article className="surface content-card"><div className="eyebrow">Before we recommend a unit</div><h2>Condition checks to ask about</h2><ul><li>Power-on and core functional checks</li><li>Screen, keyboard, ports, battery and connectivity condition</li><li>SSD/storage health and capacity</li><li>Photos of the specific unit before delivery</li><li>Included charger, accessories and operating system details</li><li>Exact cosmetic condition, serial/model and available stock</li></ul></article><article className="surface content-card"><div className="eyebrow">A sensible fit matters</div><h2>Make the trade-off clear</h2><p>We’ll talk through the intended role, acceptable cosmetic grade, useful life expectations and any available warranty or return terms for the specific product. Terms vary by item and will be confirmed in writing before purchase.</p><Link href="/warranty" className="button-quiet">Read warranty & returns notes <ArrowRight size={15}/></Link></article></div><p className="legal-note">Availability, grading standards, included accessories, warranty and returns are product-specific. No refurbished stock or specific condition is guaranteed until confirmed.</p></div></section><CtaPanel title="Looking for a particular device mix?" text="Tell us the roles, quantities and grade you are considering. We’ll discuss what may be available."/></>;
}

function InterestMiniForm() {
  const [sent,setSent] = useState(false);
  const [city,setCity] = useState('');
  return sent ? <div className="form-success" role="status"><strong>Thanks — your interest is noted here.</strong><p>This page does not send or store submissions. Please connect an inbox or backend before launch so enquiries can reach the team.</p></div> : <form onSubmit={(event)=>{event.preventDefault();setSent(true)}} className="form-grid"><div className="field"><label htmlFor="other-city">City</label><input id="other-city" required value={city} onChange={(event)=>setCity(event.target.value)} placeholder="Your city"/></div><div className="field"><label htmlFor="other-org">Organization</label><input id="other-org" placeholder="Organization or team"/></div><div className="field full"><label htmlFor="other-needs">What do you need?</label><textarea id="other-needs" required placeholder="A few words about your site or project"/></div><div className="field full"><button className="button-primary" type="submit">Enquire about this city <ArrowRight size={15}/></button><span className="form-hint">Local demo state only; not delivered or stored until connected.</span></div></form>;
}

export function CoveragePage() {
  return <><PageHero kicker="Where we work" title="North India, with scope confirmed locally." text="We are based in Noida and work with teams across Delhi NCR, Chandigarh Tricity and Punjab. Onsite availability and response terms are confirmed per project and location."/><section className="section" style={{paddingTop:0}}><div className="container-wide"><div className="location-grid">{siteConfig.coverageRegions.map((region,index)=><article className="surface location-card" key={region.label}><div className="eyebrow">0{index+1} / {index===0?'NCR':index===1?'TRICITY':'PROJECTS'}</div><h2 className="display">{region.label}</h2><div className="location-tags">{region.places.map((item)=><span key={item}>{item}</span>)}</div><p>{region.description}</p></article>)}</div><div className="content-grid" style={{marginTop:18}}><article className="surface content-card"><div className="eyebrow">A clear expectation</div><h2>Onsite & response terms</h2><p>Onsite availability, delivery, replacement and response arrangements vary by project and location. We confirm these details directly rather than promising same-week service or replacement.</p></article><article className="surface content-card"><div className="eyebrow">Further afield?</div><h2>Other cities — enquire</h2><InterestMiniForm/></article></div></div></section><CtaPanel/></>;
}

export function HowItWorksPage() {
  const steps = [['01','Talk through the need','Roles, workflows, quantities, locations and what is not working today.'],['02','Shape a practical plan','Device mix, new or refurbished options and any infrastructure requirements.'],['03','Confirm scope & quote','Availability, price, service terms and the project plan are confirmed before proceeding.'],['04','Set up & support','Deployment and any ongoing support are agreed to fit the project and location.'],['05','Plan the next refresh','Maintenance, replacement and buyback options are discussed when they are part of the agreed scope.']];
  return <><PageHero kicker="Plain process. No black box." title="A few clear steps from need to ready." text="Whether you are outfitting a startup team or planning for an institution, the process starts with understanding the work—not pushing a standard bundle."/><section className="section" style={{paddingTop:0}}><div className="container-wide"><div className="step-list">{steps.map(([n,title,text])=><article className="surface step-card" key={n}><span className="step-number">{n} / STEP</span><h3 className="display">{title}</h3><p>{text}</p></article>)}</div><div className="split-band" style={{borderRadius:22,marginTop:34}}><div className="container-wide split-inner"><div><div className="eyebrow" style={{color:'#e5ad8a'}}>Why Buy Through Us</div><h2 className="display">Useful answers. Straight talk.</h2><p>We aim to take the coordination work out of IT buying: understand the job, explain the trade-offs, confirm what is included, and keep the next steps clear.</p></div><div className="split-list"><div className="split-row"><span>Recommendations tied to real roles</span><span>01 / FIT</span></div><div className="split-row"><span>New and refurbished options to compare</span><span>02 / CHOICE</span></div><div className="split-row"><span>Scope and terms confirmed before you commit</span><span>03 / CLARITY</span></div><div className="split-row"><span>Support arrangements discussed up front</span><span>04 / FOLLOW-THROUGH</span></div></div></div></div><p className="legal-note">We do not claim a specific founding history or service guarantee. Availability and arrangements are agreed for each project.</p></div></section><CtaPanel/></>;
}

const faqs = [
  ['Who do you work with?', 'We support startups and institutional buyers, including organizations with multiple roles, departments or sites. The right scope depends on your requirements.'],
  ['Can you help us choose devices by role?', 'Yes. Tell us what people need to do and where they work. We can help build a right-sized device mix for discussion.'],
  ['Do you offer both new and refurbished stock?', 'We can discuss new and refurbished options subject to availability. Refurbished grade, condition, included accessories and terms are confirmed for the specific device.'],
  ['Can we buy devices outright?', 'Yes. A one-time purchase is one of the ways to work together. The quote depends on selected hardware, quantities, availability and any additional scope.'],
  ['What does monthly managed service include?', 'The monthly option is scoped with you. Devices, support, maintenance and replacement terms must be explicitly agreed; no fixed inclusions are assumed.'],
  ['Do you set up Wi-Fi, CCTV or auditorium AV?', 'These are capability areas we can discuss, along with networking, projectors, AV and workspace setup. Requirements and delivery scope are confirmed per project.'],
  ['Do you provide onsite support?', 'Onsite availability and response terms depend on the project and location. They are confirmed directly; we do not make a blanket same-week promise.'],
  ['Do you work outside Delhi NCR and Chandigarh?', 'Punjab project availability can be discussed. For other cities, use the enquiry form and we will assess scope and location.'],
  ['Can you supply servers or printers?', 'Servers and printers are available for discussion on request. Share the intended use and specifications you have in mind.'],
  ['How do warranty, returns and replacement work?', 'Terms vary by product and service arrangement. They should be confirmed in writing in the quote or agreement before purchase. See our draft warranty page for the current placeholder policy.'],
];
export function FaqPage() {
  const [opened,setOpened] = useState<number | null>(0);
  return <><PageHero kicker="Good questions deserve clear answers" title="A few things you may be wondering." text="If your requirement is more specific, tell us the context and we’ll work through it with you."/><section className="section" style={{paddingTop:0}}><div className="container-wide"><div className="faq-list">{faqs.map(([question,answer],index)=><div className="faq-item" key={question}><button className="faq-question" aria-expanded={opened===index} onClick={()=>setOpened(opened===index?null:index)}>{question}<ChevronDown size={19} style={{transform:opened===index?'rotate(180deg)':'none',transition:'transform .2s',flexShrink:0}}/></button>{opened===index&&<div className="faq-answer">{answer}</div>}</div>)}</div></div></section><CtaPanel/></>;
}

export function ContactPage() {
  const [sent,setSent] = useState(false);
  if (sent) return <><PageHero kicker="Message prepared" title="Thanks for sharing the context." text="Your submission is only held in this page state. It has not been sent or stored because an inbox or backend is not connected yet."/><section className="section" style={{paddingTop:0}}><div className="container-wide"><div className="form-success"><strong>Before launch: connect the contact form to a monitored inbox or backend.</strong><p>Replace the visible phone, WhatsApp, email and address placeholders with verified business details.</p><button className="button-outline" onClick={()=>setSent(false)}>Return to the form</button></div></div></section></>;
  return <><PageHero kicker="Start a conversation" title="What does your team need to get done?" text="A few details help us understand the requirement and follow up with a useful conversation. This demo form does not send or store your information."/><section className="section" style={{paddingTop:0}}><div className="container-wide content-grid"><div className="surface content-card"><div className="eyebrow">Tell us the practical bits</div><h2 className="display">The more context, the better the first conversation.</h2><p>Share the people, sites, timelines and preferences involved. We will help identify what needs confirming next.</p><div className="split-list" style={{marginTop:25}}><div className="split-row"><span>Buying preference</span><span>ONE-TIME / MONTHLY / OPEN</span></div><div className="split-row"><span>Coverage focus</span><span>NCR / TRICITY / PUNJAB</span></div></div><div className="contact-details" aria-label="Business contact details"><div className="contact-detail"><strong>WhatsApp · Kartikae Khurana</strong><span><a href={`https://wa.me/${siteConfig.whatsappNumber.replace(/\D/g, '')}`} target="_blank" rel="noreferrer">Message Kartikae on WhatsApp</a></span></div>{siteConfig.contactPeople.map((person)=><div className="contact-detail" key={person.name}><strong>{person.name}</strong><span>Phone: <a href={`tel:${person.phone}`}>{person.phone}</a></span></div>)}<div className="contact-detail"><strong>Email</strong><span><a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a></span></div><div className="contact-detail"><strong>Noida address</strong><span>{siteConfig.addresses.noida}</span></div><div className="contact-detail"><strong>Chandigarh / Mohali address</strong><span>{siteConfig.addresses.chandigarhMohali}</span></div></div></div><div className="surface content-card"><form onSubmit={(event)=>{event.preventDefault();setSent(true)}}><div className="form-grid">
      <div className="field"><label htmlFor="name">Name *</label><input id="name" required autoComplete="name" placeholder="Your name"/></div>
      <div className="field"><label htmlFor="organization">Organization *</label><input id="organization" required autoComplete="organization" placeholder="Company or institution"/></div>
      <div className="field"><label htmlFor="phone">Phone *</label><input id="phone" required type="tel" autoComplete="tel" placeholder="A number we can reach you on"/></div>
      <div className="field"><label htmlFor="email">Email *</label><input id="email" required type="email" autoComplete="email" placeholder="you@organization.org"/></div>
      <div className="field"><label htmlFor="city">City *</label><select id="city" required defaultValue=""><option value="" disabled>Select a city</option>{siteConfig.contactCities.map((city)=><option key={city}>{city}</option>)}</select></div>
      <div className="field"><label htmlFor="team-size">Team size / endpoints</label><select id="team-size" defaultValue=""><option value="" disabled>Select a range</option><option>1–10</option><option>11–30</option><option>31–100</option><option>101–500</option><option>500+</option><option>Multiple sites / unsure</option></select></div>
      <div className="field"><label htmlFor="budget">Budget range</label><input id="budget" placeholder="Optional; share a range if useful"/></div>
      <div className="field"><label htmlFor="preference">Purchase preference</label><select id="preference" defaultValue="Open to options"><option>One-time purchase</option><option>Monthly managed service</option><option>Open to options</option></select></div>
      <div className="field full" role="group" aria-labelledby="role-needs-label"><span className="field-label" id="role-needs-label">Roles or site needs</span><div className="contact-roles">{siteConfig.contactRoles.map((role)=><label className="contact-role" key={role}><input type="checkbox" name="roles" value={role}/><span>{role}</span></label>)}</div></div>
      <div className="field full"><label htmlFor="site-needs">Departments / site needs</label><input id="site-needs" placeholder="Sites, endpoints, roles or infrastructure requirements"/></div>
      <div className="field full"><label htmlFor="message">How can we help? *</label><textarea id="message" required placeholder="Devices, setup, support, timing—whatever is useful to know."/></div>
      <div className="field full"><button className="button-primary" type="submit">Review enquiry <ArrowRight size={15}/></button><span className="form-hint">Local thank-you state only. Enquiries are not delivered or stored until an inbox/backend is connected.</span></div>
    </div></form></div></div></section><CtaPanel title="Prefer to plan first?" text="Use the IT planner to create a checklist before you get in touch."/></>;
}

const policyCopy: Record<string,{kicker:string;title:string;intro:string;sections:[string,string][]}> = {
  '/privacy': { kicker:'Draft policy · review before launch',title:'Privacy policy',intro:'This draft explains how enquiry information may be handled once the website is connected to an operating inbox or backend. It is not legal advice and must be reviewed and completed before publication.',sections:[['Information you provide','A future contact form may request your name, organization, phone, email, city, team or site needs, budget preference and message. This build currently does not transmit or store form submissions.'],['Purpose and access','When connected, information should be used to respond to enquiries and plan requested services, with access limited to relevant team members. Confirm the actual lawful basis, retention period, processors and safeguards with appropriate counsel.'],['Cookies and analytics','No analytics or advertising tracking has been configured as part of this frontend. Update this section if such tools are introduced.'],['Your requests','Add verified contact details and a process for access, correction, deletion and other applicable privacy requests before launch.'],['Updates','The effective date, business identity and policy changes must be completed by the business before this draft is relied upon.']] },
  '/terms': { kicker:'Draft terms · review before launch',title:'Website & service terms',intro:'This placeholder is not a binding service agreement. Have the final terms reviewed, add the correct legal entity and make sure each customer quote or contract records its own scope.',sections:[['Website information','Website descriptions are general capability information, not an offer or guarantee of availability. Products, pricing, specifications and service scope must be confirmed in a written quote.'],['Quotes and orders','A quote should identify selected products, quantities, taxes, delivery or setup scope, payment, validity and any applicable terms. No price or order is created by using the planner or enquiry form.'],['Services and locations','Delivery, deployment, onsite availability, response, maintenance and replacement terms vary by project and location and should be recorded in the applicable written agreement.'],['Third-party products','Hardware and software may be subject to their manufacturers’ or providers’ terms. Confirm ownership, licensing, support and warranty details for each item.'],['Business details and governing terms','Insert the legal/trading name, registered address, governing law, dispute process and effective date after legal review.']] },
  '/warranty': { kicker:'Draft policy · product terms vary',title:'Warranty, returns & replacement',intro:'Warranty and return terms depend on the product, condition, supplier and service arrangement. The placeholders below are not a warranty promise or a precise return period.',sections:[['Product warranty','Applicable manufacturer or seller warranty coverage, duration, exclusions and claim steps must be confirmed for each quoted item in writing. Refurbished products may have different terms.'],['Inspection and returns','Inspect products on receipt and report any issue through the contact method specified in the relevant order documents. Return eligibility, condition requirements, shipping and timelines must be confirmed in the written quote or agreement.'],['Replacement and service','Replacement availability and timing are not guaranteed. Any replacement, repair, maintenance or response commitment must be stated in the relevant written terms for the product, project and location.'],['Before purchase','Ask us to confirm the exact product grade, included accessories, warranty provider and duration, return eligibility, exclusions and support scope before you proceed.'],['Business confirmation','Warranty period: '+siteConfig.warrantyPeriod+'. Current terms: '+siteConfig.warrantySummary+'. Return terms: '+siteConfig.returnSummary+'. These placeholders must be replaced and reviewed before publication.']] },
};
export function PolicyPage({ path }: { path: string }) {
  const policy = policyCopy[path];
  return <><PageHero kicker={policy.kicker} title={policy.title} text={policy.intro}/><section className="section" style={{paddingTop:0}}><div className="container-wide legal-content">{policy.sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}<p className="legal-note">This page is a draft placeholder and must be reviewed, completed and approved by the business before launch.</p></div></section><CtaPanel/></>;
}
